### ISSUE TITLE
Glitches on Steam Deck

### ISSUE THREAD

**Issue by minsumansu** [Unity-Technologies/com.unity.toonshader#252]
![Animation1](https://user-images.githubusercontent.com/93003473/209698312-1ddb861a-9cab-4edc-b4c9-fae39118b64b.gif)

![Animation](https://user-images.githubusercontent.com/93003473/209698576-48ff262a-ed2c-487a-ba82-129d10626dec.gif)

I made linux build with Unity LTS 2021.3.16f1 for running it on valve's steam deck.
and UTS with outlines are glitching.

I'm using URP.
Tried legacy UTS for URP and UTS3 0.8.2
and both glitches same.

**Comment by H3idi-X** [comment]
Finally, we could see the chance to Steam Deck.
We don't belive it is our issue,its valkun driver has some issues.

**Comment by minsumansu** [comment]
Thanks for your inform.
I think Windows build with Proton runs mostly okay for me now.
I'll hope Valve resolve this issue later :)

**Comment by RobProductions** [comment]
This isn't a problem with Valve or Vulkan, it's a problem with how the toon shader handles the camera depth in OpenGL vs DirectX as reported by @segurvita in the original Github repo here: https://github.com/unity3d-jp/UnityChanToonShaderVer2_Project/issues/138

It only happens when using the Z Offset feature as it gets multiplied by the incorrect Z value. For materials that don't use "Offset outline with camera Z-axis" feature (set at 0), it has no noticeable difference which is why it was difficult to find until now. One of my users reported this issue on Linux versions (OpenGL 4.6) and it's definitely happening on version 0.9.5 preview:

![Image](https://github.com/user-attachments/assets/1c5bd7de-9f80-44d6-b92e-e78da6c1d788)

@segurvita mentioned that the latest dev branch fixed it, though I don't see anything in the git history that specifically addresses it. I will update to 0.11.0 to see if that fixes it and report back

**Comment by RobProductions** [comment]
Version 0.11.0 didn't solve it, and I can see that without even building just by changing the "Auto Graphics API for Windows" to disabled and placing `OpenGLCore` at the top so that the editor runs with OpenGL instead of DX:

![Image](https://github.com/user-attachments/assets/ae19cb62-8f6d-4ca4-baa5-57084c62d868)

@H3idi-X I believe this issue needs to be reopened and looked at
