### ISSUE TITLE
Point light and outline issues

### ISSUE THREAD

**Issue by minsumansu** [Unity-Technologies/com.unity.toonshader#273]
![2023-02-25_044](https://user-images.githubusercontent.com/93003473/221354373-fa912442-f41a-4eea-a7d5-aca4166a0e22.png)
![2023-02-25_043](https://user-images.githubusercontent.com/93003473/221354376-b4603efa-695a-45eb-a81c-111384054cd9.png)

1. When there is a point light, shade appears with unwanted style.

2. Outline seems not affected by lights, because it always looks brighter in darker scenes.

**Comment by H3idi-X** [comment]
Can I ask what attached images suggest? Upper is for the point light issue and the other is for outline?

**Comment by minsumansu** [comment]
Sorry.
Upper is with point light, and the other is 'without' point light.

In bright scenes, hair outline is actually looks much darker than hair itself,
but in dark scenes, hair outline become much brighter than what I intended.

Sometimes it looks good but having options to choose would be appreciated.
Plus, HDR option for outline will be very useful so please consider.

**Comment by Nobuyuki-Kobayashi** [comment]
For correct advice, please let me know the name and version of the shader you are currently using. 
Also, for the outline environment, I need information on the version of Unity you are using, the rendering pipeline, and the Environment tab or Environment Lighting of the lighting window, so can you give me a screenshot?
![0228-09_01](https://user-images.githubusercontent.com/3204820/221722129-803aaef6-5d3a-4b41-bbcb-1cef70605781.png)

**Comment by minsumansu** [comment]
I'm using Unity Toon Shader **0.8.5-preview.**
Unity version: **2021.3.19f1**
Render pipeline: **URP**

![2023-03-01 034702](https://user-images.githubusercontent.com/93003473/221951823-0bfe0631-0563-4658-9828-9db345009c28.png)

And... I found the solution.
[Lighting]-[Environment]-[Sun Source] was the reason.
![2023-03-01_045](https://user-images.githubusercontent.com/93003473/221957200-716fcf73-71ba-4d18-9413-0b7671524385.png)
Sun source directional light was affecting outline color even though it was deactivated.
It's somewhat understandable but little confusing.


Then I noticed another issue that **Fog is not working on UTS**. 
![2023-03-01_046](https://user-images.githubusercontent.com/93003473/221957837-6b0d8340-4075-4762-b4e6-8a45692aea02.png)

I tried very intense fog on various scenes but all the same.

**Comment by Nobuyuki-Kobayashi** [comment]
Thank you for the additional information on setting up the ambient light source.
I would like to offer some itemized advice regarding your inquiry.

_1．When there is a point light, shade appears with unwanted style._

The effect of point lights can be adjusted by the Step Offset function of the Unity Toon Shader. To adjust, first, place the main directional light in the scene and then adjust the step values for each color. After you have a good value, add another point light to the scene and adjust the Step Offset function to compensate for the effect of the added point light.

Please note that shading with point lights cannot separate the steps as clearly and completely as with a directional light, due to the characteristic of point lights that their brightness attenuates with distance.

_2. Outline seems not affected by lights, because it always looks brighter in darker scenes._

Unity Toon Shadre's normal inverted object outlines are affected by the color settings in the Environment Lighting settings, not by the brightness of the scene as it appears.

In particular, if the colors in the Environment Lighting settings are set to bright colors, the colors in the Environment Lighting settings will take precedence even if the actual scene looks dark.

When you start Unity with a completely new scene, the colors in the Environment Lighting settings are set to dark gray, but if you set a brighter color while tweaking these settings yourself, the brighter color will be selected over the other color set in the Environment Lighting settings, even if the source of the Environment Lighting is Skybox.

This is a Unity specification, so users must be aware of this.

Therefore, if you do not want to make the UTS outline color brighter than necessary, not only set the outline color itself to a darker color but also be careful that the color setting in the Environmental Lighting Settings is not set to a color that is too bright.

---
Please make the fog issue a separate Issue item from this inquiry.
As a general rule, one Issue should be reported as one report.

When reporting, please also provide a screenshot of the URP's fog settings, etc.  Without seeing them, we cannot give you a correct response.

Regards.

**Comment by minsumansu** [comment]
I created a new project to reproduce this issues.
Using Unity 2021.3.19f1 and UTS 0.8.5-preview.

1.
![001](https://user-images.githubusercontent.com/93003473/222094740-a4a9fd0b-3328-423c-9f8a-6af556085cc5.png)
![002](https://user-images.githubusercontent.com/93003473/222094759-b4e2d909-6ccf-4995-97ee-f164cb1b1425.png)
Unexpected shade appears when there is point light.
Especially noticeable on the face.




![003](https://user-images.githubusercontent.com/93003473/222095184-de401ef8-c80b-49c4-a5b2-5dc578aeaf1f.png)
I tried changing 'point light step offset'
but it only shifts base shades of UTS so it did not help.

![004](https://user-images.githubusercontent.com/93003473/222096663-81d0fdcf-23e5-496e-b387-c44d5f1f334e.png)
Also found UTS's 'Light probe intensity' is producing this issue too.




2.
And for the outline issue,
When [Lighting]-[Environment]-[Sun Source] is set,
**outline color is locked by sun source's color.**
(I think referencing sun source is not intuitive and ideal.)

I reproduced those issue with a new project, so please check.
You can download via link below.

[https://drive.google.com/file/d/1EETd56_JPrMYE0UExoBqMx2sYZXd8vJ-/view?usp=sharing](url)

**Comment by minsumansu** [comment]
ok.
For light probe’s shade, it’s subtle and controllerable with ‘Light probe intensity’ that’s enough for me.

But for point light shade, I have no option to control, or reduce it.
So similar option like ‘Point light intensity’ will be very helpful.
(Reducing only shade and keep influenced color would be much nicer, if it’s possible)

Please consider for adding this feature.

Thank you.

**Comment by Nobuyuki-Kobayashi** [comment]
The request regarding point lights is within the scope of the Unity Toon Shader specification, so there are currently no plans to modify it.

Regards.
